//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_PED_CAFETERIA.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Proyecto_PED_CAFETERIA.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cuphead {
            get {
                object obj = ResourceManager.GetObject("Cuphead", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Diseño_sin_título {
            get {
                object obj = ResourceManager.GetObject("Diseño sin título", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Diseño_sin_título__1_ {
            get {
                object obj = ResourceManager.GetObject("Diseño sin título (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documento_A4_Catálogo_Supermercado_Moderno_Blanco__1_ {
            get {
                object obj = ResourceManager.GetObject("Documento A4 Catálogo Supermercado Moderno Blanco (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documento_A4_Catálogo_Supermercado_Moderno_Blanco__10_ {
            get {
                object obj = ResourceManager.GetObject("Documento A4 Catálogo Supermercado Moderno Blanco (10)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documento_A4_Catálogo_Supermercado_Moderno_Blanco__2_ {
            get {
                object obj = ResourceManager.GetObject("Documento A4 Catálogo Supermercado Moderno Blanco (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documento_A4_Catálogo_Supermercado_Moderno_Blanco__20_ {
            get {
                object obj = ResourceManager.GetObject("Documento A4 Catálogo Supermercado Moderno Blanco (20)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documento_A4_Catálogo_Supermercado_Moderno_Blanco__21_ {
            get {
                object obj = ResourceManager.GetObject("Documento A4 Catálogo Supermercado Moderno Blanco (21)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documento_A4_Catálogo_Supermercado_Moderno_Blanco__22_ {
            get {
                object obj = ResourceManager.GetObject("Documento A4 Catálogo Supermercado Moderno Blanco (22)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documento_A4_Catálogo_Supermercado_Moderno_Blanco__23_ {
            get {
                object obj = ResourceManager.GetObject("Documento A4 Catálogo Supermercado Moderno Blanco (23)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documento_A4_Catálogo_Supermercado_Moderno_Blanco__24_ {
            get {
                object obj = ResourceManager.GetObject("Documento A4 Catálogo Supermercado Moderno Blanco (24)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documento_A4_Catálogo_Supermercado_Moderno_Blanco__25_ {
            get {
                object obj = ResourceManager.GetObject("Documento A4 Catálogo Supermercado Moderno Blanco (25)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documento_A4_Catálogo_Supermercado_Moderno_Blanco__27_ {
            get {
                object obj = ResourceManager.GetObject("Documento A4 Catálogo Supermercado Moderno Blanco (27)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documento_A4_Catálogo_Supermercado_Moderno_Blanco__28_ {
            get {
                object obj = ResourceManager.GetObject("Documento A4 Catálogo Supermercado Moderno Blanco (28)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documento_A4_Catálogo_Supermercado_Moderno_Blanco__29_ {
            get {
                object obj = ResourceManager.GetObject("Documento A4 Catálogo Supermercado Moderno Blanco (29)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documento_A4_Catálogo_Supermercado_Moderno_Blanco__3_ {
            get {
                object obj = ResourceManager.GetObject("Documento A4 Catálogo Supermercado Moderno Blanco (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documento_A4_Catálogo_Supermercado_Moderno_Blanco__3_1 {
            get {
                object obj = ResourceManager.GetObject("Documento A4 Catálogo Supermercado Moderno Blanco (3)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documento_A4_Catálogo_Supermercado_Moderno_Blanco__30_ {
            get {
                object obj = ResourceManager.GetObject("Documento A4 Catálogo Supermercado Moderno Blanco (30)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documento_A4_Catálogo_Supermercado_Moderno_Blanco__31_ {
            get {
                object obj = ResourceManager.GetObject("Documento A4 Catálogo Supermercado Moderno Blanco (31)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documento_A4_Catálogo_Supermercado_Moderno_Blanco__32_ {
            get {
                object obj = ResourceManager.GetObject("Documento A4 Catálogo Supermercado Moderno Blanco (32)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documento_A4_Catálogo_Supermercado_Moderno_Blanco__33_ {
            get {
                object obj = ResourceManager.GetObject("Documento A4 Catálogo Supermercado Moderno Blanco (33)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documento_A4_Catálogo_Supermercado_Moderno_Blanco__34_ {
            get {
                object obj = ResourceManager.GetObject("Documento A4 Catálogo Supermercado Moderno Blanco (34)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documento_A4_Catálogo_Supermercado_Moderno_Blanco__35_ {
            get {
                object obj = ResourceManager.GetObject("Documento A4 Catálogo Supermercado Moderno Blanco (35)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documento_A4_Catálogo_Supermercado_Moderno_Blanco__36_ {
            get {
                object obj = ResourceManager.GetObject("Documento A4 Catálogo Supermercado Moderno Blanco (36)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documento_A4_Catálogo_Supermercado_Moderno_Blanco__37_ {
            get {
                object obj = ResourceManager.GetObject("Documento A4 Catálogo Supermercado Moderno Blanco (37)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documento_A4_Catálogo_Supermercado_Moderno_Blanco__38_ {
            get {
                object obj = ResourceManager.GetObject("Documento A4 Catálogo Supermercado Moderno Blanco (38)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documento_A4_Catálogo_Supermercado_Moderno_Blanco__39_ {
            get {
                object obj = ResourceManager.GetObject("Documento A4 Catálogo Supermercado Moderno Blanco (39)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documento_A4_Catálogo_Supermercado_Moderno_Blanco__4_ {
            get {
                object obj = ResourceManager.GetObject("Documento A4 Catálogo Supermercado Moderno Blanco (4)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documento_A4_Catálogo_Supermercado_Moderno_Blanco__40_ {
            get {
                object obj = ResourceManager.GetObject("Documento A4 Catálogo Supermercado Moderno Blanco (40)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documento_A4_Catálogo_Supermercado_Moderno_Blanco__41_ {
            get {
                object obj = ResourceManager.GetObject("Documento A4 Catálogo Supermercado Moderno Blanco (41)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documento_A4_Catálogo_Supermercado_Moderno_Blanco__42_ {
            get {
                object obj = ResourceManager.GetObject("Documento A4 Catálogo Supermercado Moderno Blanco (42)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documento_A4_Catálogo_Supermercado_Moderno_Blanco__43_ {
            get {
                object obj = ResourceManager.GetObject("Documento A4 Catálogo Supermercado Moderno Blanco (43)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documento_A4_Catálogo_Supermercado_Moderno_Blanco__44_ {
            get {
                object obj = ResourceManager.GetObject("Documento A4 Catálogo Supermercado Moderno Blanco (44)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documento_A4_Catálogo_Supermercado_Moderno_Blanco__46_ {
            get {
                object obj = ResourceManager.GetObject("Documento A4 Catálogo Supermercado Moderno Blanco (46)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documento_A4_Catálogo_Supermercado_Moderno_Blanco__47_ {
            get {
                object obj = ResourceManager.GetObject("Documento A4 Catálogo Supermercado Moderno Blanco (47)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documento_A4_Catálogo_Supermercado_Moderno_Blanco__48_ {
            get {
                object obj = ResourceManager.GetObject("Documento A4 Catálogo Supermercado Moderno Blanco (48)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documento_A4_Catálogo_Supermercado_Moderno_Blanco__48_1 {
            get {
                object obj = ResourceManager.GetObject("Documento A4 Catálogo Supermercado Moderno Blanco (48)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documento_A4_Catálogo_Supermercado_Moderno_Blanco__49_ {
            get {
                object obj = ResourceManager.GetObject("Documento A4 Catálogo Supermercado Moderno Blanco (49)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documento_A4_Catálogo_Supermercado_Moderno_Blanco__5_ {
            get {
                object obj = ResourceManager.GetObject("Documento A4 Catálogo Supermercado Moderno Blanco (5)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documento_A4_Catálogo_Supermercado_Moderno_Blanco__50_ {
            get {
                object obj = ResourceManager.GetObject("Documento A4 Catálogo Supermercado Moderno Blanco (50)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documento_A4_Catálogo_Supermercado_Moderno_Blanco__6_ {
            get {
                object obj = ResourceManager.GetObject("Documento A4 Catálogo Supermercado Moderno Blanco (6)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documento_A4_Catálogo_Supermercado_Moderno_Blanco__7_ {
            get {
                object obj = ResourceManager.GetObject("Documento A4 Catálogo Supermercado Moderno Blanco (7)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documento_A4_Catálogo_Supermercado_Moderno_Blanco__8_ {
            get {
                object obj = ResourceManager.GetObject("Documento A4 Catálogo Supermercado Moderno Blanco (8)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documento_A4_Catálogo_Supermercado_Moderno_Blanco__9_ {
            get {
                object obj = ResourceManager.GetObject("Documento A4 Catálogo Supermercado Moderno Blanco (9)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dylce_aroma_cafe_iniciooo {
            get {
                object obj = ResourceManager.GetObject("dylce aroma cafe iniciooo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dylce_aroma_cafe_iniciooo1 {
            get {
                object obj = ResourceManager.GetObject("dylce aroma cafe iniciooo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ESRTA_ES_LA_BUENA_ {
            get {
                object obj = ResourceManager.GetObject("ESRTA ES LA BUENA)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ESRTA_ES_LA_BUENA_1 {
            get {
                object obj = ResourceManager.GetObject("ESRTA ES LA BUENA)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo_empresa_cafetería_divertida_ilustrada__1_ {
            get {
                object obj = ResourceManager.GetObject("Logo empresa cafetería divertida ilustrada (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo_empresa_cafetería_divertida_ilustrada__1_1 {
            get {
                object obj = ResourceManager.GetObject("Logo empresa cafetería divertida ilustrada (1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo_empresa_cafetería_divertida_ilustrada__2_ {
            get {
                object obj = ResourceManager.GetObject("Logo empresa cafetería divertida ilustrada (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo_empresa_cafetería_divertida_ilustrada__2_1 {
            get {
                object obj = ResourceManager.GetObject("Logo empresa cafetería divertida ilustrada (2)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo_empresa_cafetería_divertida_ilustrada__2_2 {
            get {
                object obj = ResourceManager.GetObject("Logo empresa cafetería divertida ilustrada (2)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mugman {
            get {
                object obj = ResourceManager.GetObject("Mugman", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mugman__1_ {
            get {
                object obj = ResourceManager.GetObject("Mugman (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Presentación_Historia_del_Café_Ilustrado_Café_y_Beige {
            get {
                object obj = ResourceManager.GetObject("Presentación Historia del Café Ilustrado Café y Beige", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Presentación_Historia_del_Café_Ilustrado_Café_y_Beige1 {
            get {
                object obj = ResourceManager.GetObject("Presentación Historia del Café Ilustrado Café y Beige1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Presentación_Historia_del_Café_Ilustrado_Café_y_Beige2 {
            get {
                object obj = ResourceManager.GetObject("Presentación Historia del Café Ilustrado Café y Beige2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Presentación_Historia_del_Café_Ilustrado_Café_y_Beige3 {
            get {
                object obj = ResourceManager.GetObject("Presentación Historia del Café Ilustrado Café y Beige3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Presentación_Historia_del_Café_Ilustrado_Café_y_Beige4 {
            get {
                object obj = ResourceManager.GetObject("Presentación Historia del Café Ilustrado Café y Beige4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TipoUsuario {
            get {
                object obj = ResourceManager.GetObject("TipoUsuario", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TipoUsuario1 {
            get {
                object obj = ResourceManager.GetObject("TipoUsuario1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TipoUsuario2 {
            get {
                object obj = ResourceManager.GetObject("TipoUsuario2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
